#pragma once
// Interfaces
#include "interfaces/interfaces.hpp"
#include "classes/vector.h"
#include "classes/entity.hpp"
#include "classes/keyvalues.hpp"
#include "definitions.hpp"
#include "netvars.hpp"
#include "math.hpp"